url: "https://share-up.pt" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ShARE-UP" # the name of your site, e.g. ACME Corp.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/share_uporto/
  - title: facebook
    url: http://facebook.com/SHAREUniversityPorto/




# Postal address (add as many lines as necessary)
address:
  - line: 3481 FEUP
  - line: Porto, Portugal


#copyright
copyright_description: Designed by
copyright_name: Diogo Valente
copyright_url: https://www.linkedin.com/in/diogovalentepolonia/